name: Check Netty SNAPSHOTS
'on':
  push:
    branches:
    - main
permissions: read-all
jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os:
        - ubuntu-22.04
        - macos-13
        - windows-2019
        transport:
        - native
        - nio
        exclude:
        - os: windows-2019
          transport: native
        - os: macos-13
          transport: native
    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 1.8
      uses: actions/setup-java@v3
      with:
        distribution: temurin
        java-version: '8'
    - name: Build with Gradle
      run: ./gradlew clean check --no-daemon -PforceTransport=${{ matrix.transport
        }} -PforceNettyVersion='4.1.97.Final-SNAPSHOT'
